CREATE DATABASE authenticationdb;

USE authentication;

CREATE TABLE users(userid INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL);

 CREATE TABLE sessions(sessionid VARCHAR(255) PRIMARY KEY, userid INT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL,
    FOREIGN KEY(userid) REFERENCES users(userid));